### ISSUE TITLE
I Try Use But Not Working

### ISSUE THREAD

**Issue by JohanChungus** [Harshitnitw/imageSearchBot#1]
I try run app.py but say Identitation error line 45

**Comment by Harshitnitw** [comment]
You can check now, I corrected the code removing the errors. However, you need to add your API keys for the same. Thanks for showing interest!

**Comment by JohanChungus** [comment]
Ok

**Comment by JohanChungus** [comment]
But Where I put Telegram Token Bot And API Key

**Comment by dhanushreddy291** [comment]
On line 6 and 8 you can add your bot token and API Keys respectively and then run the code.

**Comment by JohanChungus** [comment]
Thanks This Is Working
